services:
  restate:
    image: docker.restate.dev/restatedev/restate:latest
    container_name: restate_dev
    ports:
      - "8080:8080"
      - "9070:9070"
      - "9071:9071"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - restate-network

  gotenberg:
    image: gotenberg/gotenberg:latest
    container_name: gotenberg_dev
    ports:
      - "3000:3000"
    networks:
      - restate-network

networks:
  restate-network:
    driver: bridge
